import os

Import("base_env CORONA_LIBS")

SConscript('cppunit-1.6.2/SConscript')

sources = [
    'CoronaTest.cpp',
    'APITests.cpp',
    'BMPTests.cpp',
    'FileTests.cpp',
    'GIFTests.cpp',
    'JPEGTests.cpp',
    'PaletteTests.cpp',
    'PCXTests.cpp',
    'PNGTests.cpp',
    'TGATests.cpp',
]

env = base_env.Copy()
env.Append(CPPPATH = ['#src', Dir('cppunit-1.6.2')],
           LIBPATH = ['#src', Dir('cppunit-1.6.2')],
           LIBS = ['cppunit'] + CORONA_LIBS)
env.Program(target = 'CoronaTest', source = sources)
