import os
from os import path

Import('base_env')

gifdir  = 'libungif-4.1.0'
jpgdir  = 'jpeg-6b'
zlibdir = 'zlib-1.1.4'
pngdir  = 'libpng-1.2.1'


SOURCES = [
    'Convert.cpp',
    'Corona.cpp',
    'Debug.cpp',
    'DefaultFileSystem.cpp',
    'MemoryFile.cpp',
    'OpenBMP.cpp',
    'OpenGIF.cpp',
    'OpenJPEG.cpp',
    'OpenPCX.cpp',
    'OpenPNG.cpp',
    'OpenTGA.cpp',
    'SavePNG.cpp',
    'SaveTGA.cpp',
] \
+ map(lambda n: gifdir + '/' + n, SConscript(dirs = gifdir)) \
+ map(lambda n: jpgdir + '/' + n, SConscript(dirs = jpgdir)) \
+ map(lambda n: zlibdir + '/' + n, SConscript(dirs = zlibdir)) \
+ map(lambda n: pngdir + '/' + n, SConscript(dirs = pngdir))

env = base_env.Copy()
cpppath = [gifdir,jpgdir,zlibdir,pngdir]
env.Append(CPPPATH = cpppath)

filename = 'corona'
Import('debug')
if debug:
	filename += '_d'

lib = env.Library(target = filename, source = SOURCES)
final = Install('../', lib)
Alias('corona',final)
