# Build Script for TachometerWidget
import os
import fnmatch


# Source files (and yes, this is indeed much like cheating)
files = os.listdir(".")
Source = fnmatch.filter(files,"*.cpp")

CPPPATH = """
	#/OpenGUI
	"""
LIBPATH_D = """
	#/lib
	"""
	
LIBPATH_R = """
	#/lib
	"""

LIBS_D = """
	OpenGUI_d.lib
	"""

LIBS_R = """
	OpenGUI.lib
	"""

OUTFILE = 'TachometerWidget'



################################################################
Import('base_env')
env = base_env.Copy()


Import('debug')
if debug:
	OUTFILE = OUTFILE + '_d'
	libpath = Split(LIBPATH_D)
	libs = Split(LIBS_D)
else:
	libpath = Split(LIBPATH_R)
	libs = Split(LIBS_R)



cppdefine = ['_USRDLL', 'TACHOMETERWIDGET_EXPORTS']
env.Append(CPPDEFINES = cppdefine)
env.Replace(CPPPATH = Split(CPPPATH))
env.Append(LIBPATH = libpath)
env.Append(LIBS = libs)


env['PDB'] = OUTFILE + '.pdb'


lib = env.SharedLibrary( OUTFILE, Source )


if debug:
	env.Install('#/bin', ['TachometerWidget_d.dll','TachometerWidget_d.pdb'] )
	env.Install('#/lib', 'TachometerWidget_d.lib')
else:
	env.Install('#/bin', ['TachometerWidget.dll','TachometerWidget.pdb'] )
	env.Install('#/lib', 'TachometerWidget.lib')

Alias('tachometer',lib)
