import os
Import('base_env')

sources = [
    'Exception.cpp',
    'NotEqualException.cpp',
    'RepeatedTest.cpp',
    'TestAssert.cpp',
    'TestCase.cpp',
    'TestFactoryRegistry.cpp',
    'TestFailure.cpp',
    'TestRegistry.cpp',
    'TestResult.cpp',
    'TestSuite.cpp',
    'TextTestResult.cpp',
    'TextTestRunner.cpp',
    'TypeInfoHelper.cpp',
]

env = base_env.Copy()
env.Append(CPPPATH = ['.'])
env.Library(target = 'cppunit', source = sources)
