
Import('base_env')
env = base_env.Copy()

if bool(env['OGRE_HOME']):
	SConscript('Renderer_Ogre/SConscript')
	SConscript('DemoO/SConscript')
else:
	print 'OGRE_HOME not found and not provided. Renderer_Ogre not available.'



