@echo Building USER HTML Docs...
@"C:\Program Files\doxygen\bin\doxygen.exe" Doxyfile > buildLog.txt 2>&1
@echo Compiling USER CHM...
@"c:\Program Files\HTML Help Workshop\hhc.exe" html\index.hhp >> buildLog.txt 2>&1
@echo DONE!