# Build Script for DemoO
import os
import fnmatch

Import('platform')
Import('debug')
Import('base_env')
env = base_env.Copy()

# Source files (and yes, this is indeed much like cheating)
files = os.listdir(".")
Source = fnmatch.filter(files,"*.cpp")

CPPPATH = """
	#/OpenGUI
	${OGRE_HOME}/include
	#/TachometerWidget
	../Renderer_Ogre
	"""
LIBPATH_D = """
	#/lib
	../lib
	${OGRE_HOME}/lib
	"""
	
LIBPATH_R = """
	#/lib
	../lib
	${OGRE_HOME}/lib
	"""

LIBS_D = """
	OpenGUI_d
	OgreMain_d
	TachometerWidget_d
	Renderer_Ogre_d
	"""

LIBS_R = """
	OpenGUI
	OgreMain
	TachometerWidget
	Renderer_Ogre
	"""

OUTFILE = 'DemoO'



################################################################

OUTFILE_orig = OUTFILE


if debug:
	OUTFILE = OUTFILE + '_d'
	libpath = Split(LIBPATH_D)
	libs = Split(LIBS_D)
else:
	libpath = Split(LIBPATH_R)
	libs = Split(LIBS_R)



env.Append(CPPPATH = Split(CPPPATH))
env.Append(LIBPATH = libpath)
env.Append(LIBS = libs)


if platform == 'win32':
	env.Append(LINKFLAGS=['/SUBSYSTEM:WINDOWS'])
	env.Append(LIBS = Split('glu32 opengl32'))



env['PDB'] = OUTFILE + '.pdb'


prog = env.Program( OUTFILE, Source )



if debug and platform == "win32":
	env.SideEffect(OUTFILE + '.ilk', prog)
	env.Clean(prog, OUTFILE + '.ilk')

final = []
if debug:
	final += env.Install('../bin/debug', prog )
	final += env.Command('../bin/debug/DemoO.zip', 'DemoO.zip', Copy('$TARGET', '$SOURCE'))
else:
	final += env.Install('../bin/release', prog )
	final += env.Command('../bin/release/DemoO.zip', 'DemoO.zip', Copy('$TARGET', '$SOURCE'))
Alias('ogre_demoo',final)
Alias('ogre',final)
Alias('all',final)
