#
# Makefile created by mfg (version 2.3)
#

TARGET =	OpenGUI.so
HEADERS =	../dependancies/tinyxml/tinystr.h \
		../dependancies/tinyxml/tinyxml.h \
		OpenGUI.h \
		OpenGUI_BaseWidgets.h \
		OpenGUI_CONFIG.h \
		OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h \
		OpenGUI_DynamicLib.h \
		OpenGUI_Element.h \
		OpenGUI_Event.h \
		OpenGUI_Exception.h \
		OpenGUI_Exports.h \
		OpenGUI_FontAtlas.h \
		OpenGUI_FontCache.h \
		OpenGUI_FontGlyph.h \
		OpenGUI_Font.h \
		OpenGUI_FontManager.h \
		OpenGUI_GenericCursor.h \
		OpenGUI_GenericResourceProvider.h \
		OpenGUI_GUISheet.h \
		OpenGUI_Imagery.h \
		OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h \
		OpenGUI_LayoutLoader.h \
		OpenGUI_LogSystem.h \
		OpenGUI_Message.h \
		OpenGUI_MouseButton.h \
		OpenGUI_Platform.h \
		OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h \
		OpenGUI_Primitives_Geometric.h \
		OpenGUI_Primitives.h \
		OpenGUI_Primitives_Mutations.h \
		OpenGUI_Primitives_Text.h \
		OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h \
		OpenGUI_RenderCache.h \
		OpenGUI_Renderer.h \
		OpenGUI_RenderOperation.h \
		OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h \
		OpenGUI_SimpleButton.h \
		OpenGUI_Singleton.h \
		OpenGUI_StaticImage.h \
		OpenGUI_Subscriber.h \
		OpenGUI_System.h \
		OpenGUI_TextLabel.h \
		OpenGUI_TextureData.h \
		OpenGUI_TextureDataRect.h \
		OpenGUI_Texture.h \
		OpenGUI_Timer.h \
		OpenGUI_TimerManager.h \
		OpenGUI_Types.h \
		OpenGUI_UnusedTypes.h \
		OpenGUI_WidgetFactoryManager.h \
		OpenGUI_Widget.h \
		OpenGUI_WidgetTemplateManager.h \
		OpenGUI_XMLParser.h \
		UnknownImage.h

SOURCES =	../dependancies/tinyxml/tinystr.cpp \
		../dependancies/tinyxml/tinyxml.cpp \
		../dependancies/tinyxml/tinyxmlerror.cpp \
		../dependancies/tinyxml/tinyxmlparser.cpp \
		../dependancies/tinyxml/xmltest.cpp \
		OpenGUI.cpp \
		OpenGUI_Cursor.cpp \
		OpenGUI_CursorManager.cpp \
		OpenGUI_DynamicLib.cpp \
		OpenGUI_Element.cpp \
		OpenGUI_Exception.cpp \
		OpenGUI_FontAtlas.cpp \
		OpenGUI_FontCache.cpp \
		OpenGUI_Font.cpp \
		OpenGUI_FontManager.cpp \
		OpenGUI_GenericCursor.cpp \
		OpenGUI_GenericResourceProvider.cpp \
		OpenGUI_GUISheet.cpp \
		OpenGUI_Imagery.cpp \
		OpenGUI_ImageryManager.cpp \
		OpenGUI_Imageset.cpp \
		OpenGUI_LayoutLoader.cpp \
		OpenGUI_LogSystem.cpp \
		OpenGUI_PluginManager.cpp \
		OpenGUI_Primitives_Geometric.cpp \
		OpenGUI_Primitives_Mutations.cpp \
		OpenGUI_Primitives_Text.cpp \
		OpenGUI_PropertySet.cpp \
		OpenGUI_RenderCache.cpp \
		OpenGUI_Renderer.cpp \
		OpenGUI_RenderOperation.cpp \
		OpenGUI_SimpleButton.cpp \
		OpenGUI_StaticImage.cpp \
		OpenGUI_System.cpp \
		OpenGUI_TextLabel.cpp \
		OpenGUI_Texture.cpp \
		OpenGUI_TextureData.cpp \
		OpenGUI_TextureDataRect.cpp \
		OpenGUI_Timer.cpp \
		OpenGUI_TimerManager.cpp \
		OpenGUI_Widget.cpp \
		OpenGUI_WidgetFactoryManager.cpp \
		OpenGUI_WidgetTemplateManager.cpp \
		OpenGUI_XMLParser.cpp

OBJECTS =	../dependancies/tinyxml/tinystr.o \
		../dependancies/tinyxml/tinyxml.o \
		../dependancies/tinyxml/tinyxmlerror.o \
		../dependancies/tinyxml/tinyxmlparser.o \
		../dependancies/tinyxml/xmltest.o \
		OpenGUI.o \
		OpenGUI_Cursor.o \
		OpenGUI_CursorManager.o \
		OpenGUI_DynamicLib.o \
		OpenGUI_Element.o \
		OpenGUI_Exception.o \
		OpenGUI_FontAtlas.o \
		OpenGUI_FontCache.o \
		OpenGUI_Font.o \
		OpenGUI_FontManager.o \
		OpenGUI_GenericCursor.o \
		OpenGUI_GenericResourceProvider.o \
		OpenGUI_GUISheet.o \
		OpenGUI_Imagery.o \
		OpenGUI_ImageryManager.o \
		OpenGUI_Imageset.o \
		OpenGUI_LayoutLoader.o \
		OpenGUI_LogSystem.o \
		OpenGUI_PluginManager.o \
		OpenGUI_Primitives_Geometric.o \
		OpenGUI_Primitives_Mutations.o \
		OpenGUI_Primitives_Text.o \
		OpenGUI_PropertySet.o \
		OpenGUI_RenderCache.o \
		OpenGUI_Renderer.o \
		OpenGUI_RenderOperation.o \
		OpenGUI_SimpleButton.o \
		OpenGUI_StaticImage.o \
		OpenGUI_System.o \
		OpenGUI_TextLabel.o \
		OpenGUI_Texture.o \
		OpenGUI_TextureData.o \
		OpenGUI_TextureDataRect.o \
		OpenGUI_Timer.o \
		OpenGUI_TimerManager.o \
		OpenGUI_Widget.o \
		OpenGUI_WidgetFactoryManager.o \
		OpenGUI_WidgetTemplateManager.o \
		OpenGUI_XMLParser.o


CLEAN =		../dependancies/tinyxml/tinystr.o \
		../dependancies/tinyxml/tinyxml.o \
		../dependancies/tinyxml/tinyxmlerror.o \
		../dependancies/tinyxml/tinyxmlparser.o \
		../dependancies/tinyxml/xmltest.o \
		OpenGUI.o \
		OpenGUI_Cursor.o \
		OpenGUI_CursorManager.o \
		OpenGUI_DynamicLib.o \
		OpenGUI_Element.o \
		OpenGUI_Exception.o \
		OpenGUI_FontAtlas.o \
		OpenGUI_FontCache.o \
		OpenGUI_Font.o \
		OpenGUI_FontManager.o \
		OpenGUI_GenericCursor.o \
		OpenGUI_GenericResourceProvider.o \
		OpenGUI_GUISheet.o \
		OpenGUI_Imagery.o \
		OpenGUI_ImageryManager.o \
		OpenGUI_Imageset.o \
		OpenGUI_LayoutLoader.o \
		OpenGUI_LogSystem.o \
		OpenGUI_PluginManager.o \
		OpenGUI_Primitives_Geometric.o \
		OpenGUI_Primitives_Mutations.o \
		OpenGUI_Primitives_Text.o \
		OpenGUI_PropertySet.o \
		OpenGUI_RenderCache.o \
		OpenGUI_Renderer.o \
		OpenGUI_RenderOperation.o \
		OpenGUI_SimpleButton.o \
		OpenGUI_StaticImage.o \
		OpenGUI_System.o \
		OpenGUI_TextLabel.o \
		OpenGUI_Texture.o \
		OpenGUI_TextureData.o \
		OpenGUI_TextureDataRect.o \
		OpenGUI_Timer.o \
		OpenGUI_TimerManager.o \
		OpenGUI_Widget.o \
		OpenGUI_WidgetFactoryManager.o \
		OpenGUI_WidgetTemplateManager.o \
		OpenGUI_XMLParser.o

#>		--- do not remove this line ---
AR =		ar
ARFLAGS =	cr
# CC =		gcc
CFLAGS =	-Wall -g
CPPFLAGS =
DEFS =
DISTCLEAN =
EXEEXT =
INCLUDES =	 -I ../dependancies/tinyxml -I ../dependancies/corona-linux/src \
		-I ../dependancies/freetype2/include
INSTALL =	install -c
INSTALL_DATA =	$(INSTALL) -m 644
INSTALL_PROGRAM =	$(INSTALL) -s
LDFLAGS =	-shared
LEX =		lex
LIBS =		# -lm -lobjc
LIBTOOL =	libtool $(LTFLAGS)
LPR =		lpr -h
PROGRAMS =	$(OBJECTS:.o= )
RANLIB =	ranlib
RM =		rm -f
VERSION =	0
YACC =		yacc

prefix =	/usr/local
bindir =	$(prefix)/bin
libdir =	$(prefix)/lib
mandir =	$(prefix)/man

COMPILE =	$(CC) -c $(CFLAGS) $(DEFS) $(INCLUDES) $(CPPFLAGS)

.SUFFIXES:	.l .y .m .cc .cpp
.c.o:
		$(COMPILE) $< -o $@
.m.o:
		$(COMPILE) $< -o $@
.cc.o:
		$(COMPILE) $< -o $@
.cpp.o:
		$(COMPILE) $< -o $@
.l.c:
		$(LEX) $(LFLAGS) -t $< >$@
.y.c:
		$(YACC) $(YFLAGS) -d $<
		mv y.tab.c $*.c
		cmp -s y.tab.h $*.h || cp y.tab.h $*.h
.y.h:
		$(YACC) $(YFLAGS) -d $<
		mv y.tab.c $*.c
		cmp -s y.tab.h $*.h || cp y.tab.h $*.h

SHELL =		/bin/sh

$(TARGET):	$(OBJECTS) $(ADDLIBS)
		$(CC) $(LDFLAGS) $(OBJECTS) $(ADDLIBS) $(LIBS) -o $@

check:		$(TARGET)

clean:
		$(RM) $(CLEAN) $(TARGET) $(TARGET)$(EXEEXT) core

distclean:	clean
		$(RM) $(DISTCLEAN)

print:
		$(LPR) $(HEADERS) $(SOURCES)

install:	$(TARGET)
		$(INSTALL) -d $(bindir)
		$(INSTALL_PROGRAM) $(TARGET)$(EXEEXT) $(bindir)

uninstall:
		$(RM) $(bindir)/$(TARGET)$(EXEEXT)

#>		--- do not remove this line ---

Force_Update:

../dependancies/tinyxml/tinystr.o:	../dependancies/tinyxml/tinystr.cpp

../dependancies/tinyxml/tinyxml.o:	../dependancies/tinyxml/tinyxml.cpp

../dependancies/tinyxml/tinyxmlerror.o:	../dependancies/tinyxml/tinyxmlerror.cpp

../dependancies/tinyxml/tinyxmlparser.o:	../dependancies/tinyxml/tinyxmlparser.cpp

../dependancies/tinyxml/xmltest.o:	../dependancies/tinyxml/xmltest.cpp

OpenGUI.o:	OpenGUI.cpp OpenGUI_Platform.h OpenGUI_PreRequisites.h

OpenGUI_Cursor.o:	OpenGUI_Cursor.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_CursorManager.o:	OpenGUI_CursorManager.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_DynamicLib.o:	OpenGUI_DynamicLib.cpp OpenGUI_DynamicLib.h \
		OpenGUI_Exception.h OpenGUI_Exports.h OpenGUI_Platform.h \
		OpenGUI_PreRequisites.h

OpenGUI_Element.o:	OpenGUI_Element.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_GUISheet.o:	OpenGUI_GUISheet.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_GenericCursor.o:	OpenGUI_GenericCursor.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_GenericResourceProvider.o:	OpenGUI_GenericResourceProvider.cpp OpenGUI.h \
		OpenGUI_Cursor.h OpenGUI_CursorManager.h \
		OpenGUI_DynamicLib.h OpenGUI_Element.h OpenGUI_Event.h \
		OpenGUI_Exception.h OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_Imagery.o:	OpenGUI_Imagery.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_ImageryManager.o:	OpenGUI_ImageryManager.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h UnknownImage.h

OpenGUI_Imageset.o:	OpenGUI_Imageset.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_PluginManager.o:	OpenGUI_PluginManager.cpp OpenGUI_DynamicLib.h \
		OpenGUI_Exception.h OpenGUI_Exports.h OpenGUI_Platform.h \
		OpenGUI_PluginManager.h OpenGUI_PreRequisites.h \
		OpenGUI_Singleton.h

OpenGUI_PropertySet.o:	OpenGUI_PropertySet.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_RenderOperation.o:	OpenGUI_RenderOperation.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_Renderer.o:	OpenGUI_Renderer.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_SimpleButton.o:	OpenGUI_SimpleButton.cpp OpenGUI.h OpenGUI_BaseWidgets.h \
		OpenGUI_Cursor.h OpenGUI_CursorManager.h \
		OpenGUI_DynamicLib.h OpenGUI_Element.h OpenGUI_Event.h \
		OpenGUI_Exception.h OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_SimpleButton.h \
		OpenGUI_Singleton.h OpenGUI_StaticImage.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_StaticImage.o:	OpenGUI_StaticImage.cpp OpenGUI.h OpenGUI_BaseWidgets.h \
		OpenGUI_Cursor.h OpenGUI_CursorManager.h \
		OpenGUI_DynamicLib.h OpenGUI_Element.h OpenGUI_Event.h \
		OpenGUI_Exception.h OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_SimpleButton.h \
		OpenGUI_Singleton.h OpenGUI_StaticImage.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_System.o:	OpenGUI_System.cpp OpenGUI.h OpenGUI_BaseWidgets.h \
		OpenGUI_Cursor.h OpenGUI_CursorManager.h \
		OpenGUI_DynamicLib.h OpenGUI_Element.h OpenGUI_Event.h \
		OpenGUI_Exception.h OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_SimpleButton.h \
		OpenGUI_Singleton.h OpenGUI_StaticImage.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_Texture.o:	OpenGUI_Texture.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_TextureData.o:	OpenGUI_TextureData.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_Timer.o:	OpenGUI_Timer.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_TimerManager.o:	OpenGUI_TimerManager.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_Widget.o:	OpenGUI_Widget.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h

OpenGUI_WidgetFactoryManager.o:	OpenGUI_WidgetFactoryManager.cpp OpenGUI.h OpenGUI_Cursor.h \
		OpenGUI_CursorManager.h OpenGUI_DynamicLib.h \
		OpenGUI_Element.h OpenGUI_Event.h OpenGUI_Exception.h \
		OpenGUI_Exports.h OpenGUI_GUISheet.h \
		OpenGUI_GenericCursor.h OpenGUI_GenericResourceProvider.h \
		OpenGUI_Imagery.h OpenGUI_ImageryManager.h \
		OpenGUI_Imageset.h OpenGUI_Message.h OpenGUI_MouseButton.h \
		OpenGUI_Platform.h OpenGUI_PluginManager.h \
		OpenGUI_PreRequisites.h OpenGUI_PropertySet.h \
		OpenGUI_RefPtr.h OpenGUI_RenderOperation.h \
		OpenGUI_Renderer.h OpenGUI_Resource.h \
		OpenGUI_ResourceProvider.h OpenGUI_Singleton.h \
		OpenGUI_Subscriber.h OpenGUI_System.h OpenGUI_Texture.h \
		OpenGUI_TextureData.h OpenGUI_Timer.h \
		OpenGUI_TimerManager.h OpenGUI_Types.h OpenGUI_Widget.h \
		OpenGUI_WidgetFactoryManager.h
